# Without running the following code, what do you think it will do?

# def foo(first, second=3, third):
#     print(first)
#     print(second)
#     print(third)

# foo(42)

This will give an error. There is no default value for the last argument. With default values for arguments, once you have set one, the rest of the arguments must also have default values.